ip = "172.17.0.1"
federation = "dementia"
log_level = "DEBUG"
framework_log_level ="INFO"

flower_algorithm_folders = "./exaflow/algorithms/flower,./tests/algorithms/flower"
exareme3_algorithm_folders = "./exaflow/algorithms/exareme3,./tests/algorithms/exareme3"

worker_landscape_aggregator_update_interval = 3000
worker_tasks_timeout = 20

[flower]
enabled = true
execution_timeout = 60
server_port = 8080

[controller]
port = 5000

[privacy]
minimum_row_count = 10
protect_local_data = false

[aggregation_server]
enabled = true
port = 50051
max_grpc_connections = 10
max_wait_for_aggregation_inputs = 10

[smpc]
enabled=false
optional=false
get_result_interval = 10
get_result_max_retries = 100
smpc_image="gpikra/coordinator:v7.0.7.4"
db_image="mongo:5.0.8"
queue_image="redis:alpine3.15"
[smpc.dp]
enabled = false
# sensitivity = 1
# privacy_budget = 0.1

[[workers]]
id = "globalworker"
role = "GLOBALWORKER"
grpc_port=5670

[[workers]]
id = "localworker1"
role = "LOCALWORKER"
grpc_port=5671
smpc_client_port=9001

[[workers]]
id = "localworker2"
role = "LOCALWORKER"
grpc_port=5672
smpc_client_port=9002
