identifier = "$WORKER_IDENTIFIER"
role = "$WORKER_ROLE"
federation = "$FEDERATION"

data_path = "$DATA_PATH"

log_level = "$LOG_LEVEL"
framework_log_level = "$FRAMEWORK_LOG_LEVEL"

[controller]
ip = "$CONTROLLER_IP"
port = "$CONTROLLER_PORT"

[privacy]
minimum_row_count = 10
protect_local_data = "$PROTECT_LOCAL_DATA"

[celery]
worker_concurrency = 16
tasks_timeout="$CELERY_TASKS_TIMEOUT"
run_udf_task_timeout="$CELERY_TASKS_TIMEOUT"

[rabbitmq]
ip = "$RABBITMQ_IP"
port = "$RABBITMQ_PORT"
user = "user"
password = "password"
vhost = "user_vhost"

[aggregation_server]
enabled = "$AGGREGATION_SERVER_ENABLED"

[data_loader]
folder = "$DATA_LOADER_FOLDER"
auto_load = "$DATA_LOADER_AUTO_LOAD"

[smpc]
enabled = "$SMPC_ENABLED"
optional = "$SMPC_OPTIONAL"
client_id = "$SMPC_CLIENT_ID"
client_address = "$SMPC_CLIENT_ADDRESS"
coordinator_address = "$SMPC_COORDINATOR_ADDRESS"
