node_identifier = "$NODE_IDENTIFIER"
federation = "$FEDERATION"

log_level = "$LOG_LEVEL"
framework_log_level = "$FRAMEWORK_LOG_LEVEL"

deployment_type="$DEPLOYMENT_TYPE"

worker_landscape_aggregator_update_interval="$WORKER_LANDSCAPE_AGGREGATOR_UPDATE_INTERVAL"

[flower]
enabled = "$FLOWER_ENABLED"
execution_timeout="$FLOWER_EXECUTION_TIMEOUT"
server_port="$FLOWER_SERVER_PORT"

[cleanup]
contextids_cleanup_folder="$CLEANUP_FOLDER"
workers_cleanup_interval="$WORKERS_CLEANUP_INTERVAL"
contextid_release_timelimit="$WORKERS_CLEANUP_CONTEXTID_RELEASE_TIMELIMIT"

[localworkers]
config_file="$LOCALWORKERS_CONFIG_FILE"
dns="$LOCALWORKERS_DNS"
port="$LOCALWORKERS_PORT"

[grpc]
tasks_timeout="$WORKER_TASKS_TIMEOUT"
cleanup_task_timeout="$WORKER_CLEANUP_TASK_TIMEOUT"
run_udf_task_timeout="$WORKER_RUN_UDF_TASK_TIMEOUT"
tasks_max_retries=3
tasks_interval_start=0
tasks_interval_step=0.2
tasks_interval_max=0.5

[aggregation_server]
enabled = "$AGGREGATION_SERVER_ENABLED"

[smpc]
enabled = "$SMPC_ENABLED"
optional = "$SMPC_OPTIONAL"
coordinator_address = "$SMPC_COORDINATOR_ADDRESS"
get_result_interval = "$SMPC_GET_RESULT_INTERVAL"
get_result_max_retries = "$SMPC_GET_RESULT_MAX_RETRIES"
[smpc.dp]
enabled = "$DP_ENABLED"
sensitivity = "$DP_SENSITIVITY"
privacy_budget = "$DP_PRIVACY_BUDGET"
