apiVersion: apps/v1
kind: Deployment
metadata:
  name: exaflow-controller-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: exaflow-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exaflow-controller
  template:
    metadata:
      labels:
        app: exaflow-controller
    spec:
      {{- if not .Values.managed_cluster }}
      nodeSelector:
        master: "true"
      {{- end }}

      containers:
      - name: controller
        image: {{ .Values.exaflow_images.repository }}/exaflow_controller:{{ .Values.exaflow_images.version }}
        ports:
          - containerPort: 5000

        env:
        - name: NODE_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FEDERATION
          value: {{ .Values.federation }}
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        - name: FRAMEWORK_LOG_LEVEL
          value: {{ .Values.framework_log_level }}
        - name: DEPLOYMENT_TYPE
          value: "KUBERNETES"
        - name: WORKER_LANDSCAPE_AGGREGATOR_UPDATE_INTERVAL
          value: {{ quote .Values.controller.worker_landscape_aggregator_update_interval }}
        - name: FLOWER_ENABLED
          value: {{ quote .Values.flower.enabled }}
        - name: FLOWER_EXECUTION_TIMEOUT
          value: {{ quote .Values.flower.execution_timeout }}
        - name: FLOWER_SERVER_PORT
          value: {{ quote .Values.flower.server_port }}
        - name: WORKERS_CLEANUP_INTERVAL
          value: {{ quote .Values.controller.workers_cleanup_interval }}
        - name: WORKERS_CLEANUP_CONTEXTID_RELEASE_TIMELIMIT
          value: "86400"  # One day in seconds
        - name: WORKER_TASKS_TIMEOUT
          value: {{ quote .Values.controller.worker_tasks_timeout }}
        - name: AGGREGATION_SERVER_ENABLED
          value: {{ quote .Values.aggregation_server.enabled }}
        - name: AGGREGATION_SERVER_DNS
          value: {{ quote .Values.aggregation_server.dns }}
        - name: LOCALWORKERS_DNS
          value: {{ quote .Values.controller.workers_dns }}
        - name: LOCALWORKERS_PORT
          value: "5672"
        - name: SMPC_ENABLED
          value: {{ quote .Values.smpc.enabled }}
        {{- if .Values.smpc.enabled }}
        - name: SMPC_OPTIONAL
          value: {{ quote .Values.smpc.optional }}
        - name: SMPC_COORDINATOR_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SMPC_COORDINATOR_ADDRESS
          value: "http://$(SMPC_COORDINATOR_IP):12314"
        - name: SMPC_GET_RESULT_INTERVAL
          value: {{ quote .Values.smpc.get_result_interval }}
        - name: SMPC_GET_RESULT_MAX_RETRIES
          value: {{ quote .Values.smpc.get_result_max_retries }}
        {{- end }}
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: {{ .Values.controller.worker_tasks_timeout }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          periodSeconds: 30
          timeoutSeconds: {{ .Values.controller.worker_tasks_timeout }}

      ### --- SMPC components ---
      {{ if .Values.smpc.enabled }}
      - name: smpc-db
        image: {{ .Values.smpc.db_image}}
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "sysadmin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123qwe"

      - name: smpc-queue
        image: {{ .Values.smpc.queue_image }}
        command: ["redis-server", "--requirepass", "agora"]
        ports:
          - containerPort: 6379
        env:
        - name: REDIS_REPLICATION_MODE
          value: "master"

      - name: smpc-coordinator
        image: {{ .Values.smpc.image }}
        command: ["python", "coordinator.py"]
        ports:
          - containerPort: 12314
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DB_URL
          value: "$(POD_IP):27017"
        - name: DB_UNAME
          value: "sysadmin"
        - name: DB_PSWD
          value: "123qwe"
        - name: REDIS_HOST
          value: "$(POD_IP)"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PSWD
          value: "agora"
        - name: PLAYER_IP_0
          value: exaflow-smpc-player0-service
        - name: PLAYER_REPO_0
          value: "http://$(PLAYER_IP_0):7000"
        - name: PLAYER_IP_1
          value: exaflow-smpc-player1-service
        - name: PLAYER_REPO_1
          value: "http://$(PLAYER_IP_1):7001"
        - name: PLAYER_IP_2
          value: exaflow-smpc-player2-service
        - name: PLAYER_REPO_2
          value: "http://$(PLAYER_IP_2):7002"
      {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-controller-service
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.managed_cluster }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: exaflow-controller
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      {{- if not .Values.managed_cluster }}
      nodePort: 30000
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-workers-service
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: exaflow-worker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672


{{- if .Values.smpc.enabled }}
---

### --- SMPC Coordinator Service ---
apiVersion: v1
kind: Service
metadata:
  name: exaflow-smpc-coordinator-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: exaflow-controller
  ports:
    - protocol: TCP
      port: 12314
      targetPort: 12314
#      nodePort: 31000  # Used for SMPC cluster debugging


### --- SMPC Coordinator DB ---

---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-smpc-coordinator-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: exaflow-controller
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


### --- SMPC Player Pods ---
---
apiVersion: v1
kind: Pod
metadata:
  name: exaflow-smpc-player0
  labels:
    app: exaflow-smpc-players
    smpc_player: player0
spec:
  nodeSelector:
    smpc_player: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - exaflow-smpc-players
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: smpc-player
    image: {{ .Values.smpc.image}}
    imagePullPolicy: IfNotPresent
    command: ["python", "player.py", "0"]
    ports:
      - containerPort: 6000
      - containerPort: 7000
      - containerPort: 14000
    env:
    - name: COORDINATOR_IP
      value: exaflow-smpc-coordinator-service
    - name: COORDINATOR_URL
      value: "http://$(COORDINATOR_IP):12314"
    - name: DB_IP
      value: exaflow-smpc-coordinator-db-service
    - name: DB_URL
      value: "$(DB_IP):27017"
    - name: DB_UNAME
      value: "sysadmin"
    - name: DB_PSWD
      value: "123qwe"
    - name: PORT
      value: "7000"
    - name: PLAYER_IP_0
      value: exaflow-smpc-player0-service
    - name: PLAYER_REPO_0
      value: "http://$(PLAYER_IP_0):7000"
    - name: PLAYER_IP_1
      value: exaflow-smpc-player1-service
    - name: PLAYER_REPO_1
      value: "http://$(PLAYER_IP_1):7001"
    - name: PLAYER_IP_2
      value: exaflow-smpc-player2-service
    - name: PLAYER_REPO_2
      value: "http://$(PLAYER_IP_2):7002"

---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-smpc-player0-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    smpc_player: player0
  ports:
    - name: port-6000
      protocol: TCP
      port: 6000
      targetPort: 6000
    - name: port-7000
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: port-14000
      protocol: TCP
      port: 14000
      targetPort: 14000

---

apiVersion: v1
kind: Pod
metadata:
  name: exaflow-smpc-player1
  labels:
    app: exaflow-smpc-players
    smpc_player: player1
spec:
  nodeSelector:
    smpc_player: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - exaflow-smpc-players
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: smpc-player
    image: {{ .Values.smpc.image}}
    imagePullPolicy: IfNotPresent
    command: ["python", "player.py", "1"]
    ports:
      - containerPort: 6001
      - containerPort: 7001
      - containerPort: 14001
    env:
    - name: COORDINATOR_IP
      value: exaflow-smpc-coordinator-service
    - name: COORDINATOR_URL
      value: "http://$(COORDINATOR_IP):12314"
    - name: DB_IP
      value: exaflow-smpc-coordinator-db-service
    - name: DB_URL
      value: "$(DB_IP):27017"
    - name: DB_UNAME
      value: "sysadmin"
    - name: DB_PSWD
      value: "123qwe"
    - name: PORT
      value: "7000"
    - name: PLAYER_IP_0
      value: exaflow-smpc-player0-service
    - name: PLAYER_REPO_0
      value: "http://$(PLAYER_IP_0):7000"
    - name: PLAYER_IP_1
      value: exaflow-smpc-player1-service
    - name: PLAYER_REPO_1
      value: "http://$(PLAYER_IP_1):7001"
    - name: PLAYER_IP_2
      value: exaflow-smpc-player2-service
    - name: PLAYER_REPO_2
      value: "http://$(PLAYER_IP_2):7002"

---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-smpc-player1-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    smpc_player: player1
  ports:
    - name: port-6001
      protocol: TCP
      port: 6001
      targetPort: 6001
    - name: port-7001
      protocol: TCP
      port: 7001
      targetPort: 7001
    - name: port-14001
      protocol: TCP
      port: 14001
      targetPort: 14001

---

apiVersion: v1
kind: Pod
metadata:
  name: exaflow-smpc-player2
  labels:
    app: exaflow-smpc-players
    smpc_player: player2
spec:
  nodeSelector:
    smpc_player: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - exaflow-smpc-players
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: smpc-player
    image: {{ .Values.smpc.image}}
    imagePullPolicy: IfNotPresent
    command: ["python", "player.py", "2"]
    ports:
      - containerPort: 6002
      - containerPort: 7002
      - containerPort: 14002
    env:
    - name: COORDINATOR_IP
      value: exaflow-smpc-coordinator-service
    - name: COORDINATOR_URL
      value: "http://$(COORDINATOR_IP):12314"
    - name: DB_IP
      value: exaflow-smpc-coordinator-db-service
    - name: DB_URL
      value: "$(DB_IP):27017"
    - name: DB_UNAME
      value: "sysadmin"
    - name: DB_PSWD
      value: "123qwe"
    - name: PORT
      value: "7000"
    - name: PLAYER_IP_0
      value: exaflow-smpc-player0-service
    - name: PLAYER_REPO_0
      value: "http://$(PLAYER_IP_0):7000"
    - name: PLAYER_IP_1
      value: exaflow-smpc-player1-service
    - name: PLAYER_REPO_1
      value: "http://$(PLAYER_IP_1):7001"
    - name: PLAYER_IP_2
      value: exaflow-smpc-player2-service
    - name: PLAYER_REPO_2
      value: "http://$(PLAYER_IP_2):7002"

---

apiVersion: v1
kind: Service
metadata:
  name: exaflow-smpc-player2-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    smpc_player: player2
  ports:
    - name: port-6002
      protocol: TCP
      port: 6002
      targetPort: 6002
    - name: port-7002
      protocol: TCP
      port: 7002
      targetPort: 7002
    - name: port-14002
      protocol: TCP
      port: 14002
      targetPort: 14002
{{ end }}
