{{- if gt (int .Values.localnodes) 0 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exaflow-localworker
  namespace: {{ .Values.namespace }}
  labels:
    app: exaflow-worker
    nodeType: localworker
spec:
  serviceName: "exaflow-worker"
  replicas: {{ .Values.localnodes }}
  selector:
    matchLabels:
      app: exaflow-worker
      nodeType: localworker
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: exaflow-worker
        nodeType: localworker
    spec:
      {{ if not .Values.managed_cluster }}
      nodeSelector:
        worker: "true"
      {{ end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: nodeType
                operator: In
                values:
                - localworker
            topologyKey: kubernetes.io/hostname
      # HostPath volumes if hostPath selected
      {{ if not .Values.managed_cluster }}
      volumes:
        - name: csv-data
          hostPath:
            path: {{ printf "%s/csvs" .Values.storage.hostPath.db.localworker }}
      {{ end }}

      containers:
      - name: worker
        image: {{ .Values.exaflow_images.repository }}/exaflow_worker:{{ .Values.exaflow_images.version }}
        volumeMounts:
        - mountPath: /opt/data
          name: csv-data
        env:
        - name: WORKER_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WORKER_ROLE
          value: "LOCALWORKER"
        - name: FEDERATION
          value: {{ .Values.federation }}
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        - name: FRAMEWORK_LOG_LEVEL
          value: {{ .Values.framework_log_level }}
        - name: CONTROLLER_IP
          value: $(EXAFLOW_CONTROLLER_SERVICE_SERVICE_HOST)
        - name: CONTROLLER_PORT
          value: $(EXAFLOW_CONTROLLER_SERVICE_SERVICE_PORT)
        - name: WORKER_TASKS_TIMEOUT
          value: {{ quote .Values.controller.worker_tasks_timeout }}
        - name: DUCKDB_PATH
          value: "/opt/data/data_models.duckdb"
        - name: GRPC_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: "5672"
        - name: AGGREGATION_SERVER_ENABLED
          value: {{ quote .Values.aggregation_server.enabled }}
        - name: AGGREGATION_SERVER_DNS
          value: {{ quote .Values.aggregation_server.dns }}
        - name: SMPC_ENABLED
          value: {{ quote .Values.smpc.enabled }}
        {{ if .Values.smpc.enabled }}
        - name: SMPC_OPTIONAL
          value: {{ quote .Values.smpc.optional }}
        - name: SMPC_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SMPC_CLIENT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SMPC_CLIENT_ADDRESS
          value: "http://$(SMPC_CLIENT_IP):9000"
        {{ end }}
        startupProbe:
          exec:
            command:
              - python
              - -m
              - exaflow.worker.healthcheck
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
              - python
              - -m
              - exaflow.worker.healthcheck
          periodSeconds: 30
          timeoutSeconds: 10

      {{ if .Values.smpc.enabled }}
      - name: smpc-client
        image: {{ .Values.smpc.image }}
        command: ["python", "client.py"]
        ports:
          - containerPort: 9000
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PORT
          value: "9000"
        - name: COORDINATOR_IP
          value: exaflow-smpc-coordinator-service
        - name: COORDINATOR_URL
          value: "http://$(COORDINATOR_IP):12314"
        - name: PLAYER_IP_0
          value: exaflow-smpc-player0-service
        - name: PLAYER_REPO_0
          value: "http://$(PLAYER_IP_0):7000"
        - name: PLAYER_IP_1
          value: exaflow-smpc-player1-service
        - name: PLAYER_REPO_1
          value: "http://$(PLAYER_IP_1):7001"
        - name: PLAYER_IP_2
          value: exaflow-smpc-player2-service
        - name: PLAYER_REPO_2
          value: "http://$(PLAYER_IP_2):7002"
      {{ end }}

  {{- if .Values.managed_cluster }}
  volumeClaimTemplates:
    - metadata:
        name: csv-data
        annotations:
          # tells Argo CD: do not prune (delete) this resource
          argocd.argoproj.io/sync-options: Delete=false,Prune=false
      spec:
        storageClassName: {{ .Values.storage.cephfs.storageClassName }}
        accessModes:
          - {{ index .Values.storage.cephfs.localworker.csvs.accessModes 0 }}
        resources:
          requests:
            storage: {{ .Values.storage.cephfs.localworker.csvs.size }}

  {{- end }}
#---  # Used for SMPC cluster debugging
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: exaflow-worker-service
#  namespace: {{ .Values.namespace }}
#spec:
#  type: LoadBalancer
#  selector:
#    app: exaflow-worker
#  ports:
#    - protocol: TCP
#      port: 9000
#      targetPort: 9000
#      nodePort: 32000
{{- end }}
