log_level = "$LOG_LEVEL"
framework_log_level = "$FRAMEWORK_LOG_LEVEL"

cdes_metadata_path = "$CDES_METADATA_PATH"

deployment_type="$DEPLOYMENT_TYPE"

node_registry_update_interval="$NODE_REGISTRY_UPDATE_INTERVAL"

[cleanup]
contextids_cleanup_file="/tmp/contextids_cleanup.toml"
nodes_cleanup_interval=10
contextid_release_timelimit=3600 #an hour

[localnodes]
config_file="$LOCALNODES_CONFIG_FILE"
dns="$LOCALNODES_DNS"
port="$LOCALNODES_PORT"

[rabbitmq]
user = "user"
password = "password"
vhost = "user_vhost"
celery_tasks_timeout="$CELERY_TASKS_TIMEOUT"
celery_tasks_max_retries=3
celery_tasks_interval_start=0
celery_tasks_interval_step=0.2
celery_tasks_interval_max=0.5

[smpc]
enabled = "$SMPC_ENABLED"
optional = "$SMPC_OPTIONAL"
coordinator_address = "$SMPC_COORDINATOR_ADDRESS"
