identifier = "localnode1"
log_level = "INFO"

[celery]
worker_concurrency = 1
task_soft_time_limit = 30
task_time_limit = 60
run_udf_soft_time_limit = 60
run_udf_time_limit = 120

[rabbitmq]
ip = "127.0.0.1"
port = "5672"
user = "user"
password = "password"
vhost = "user_vhost"

[monetdb]
ip = "127.0.0.1"
port = "50000"
database = "db"
username = "monetdb"
password = "monetdb"
