identifier = "$NODE_IDENTIFIER"
log_level = "$LOG_LEVEL"
role = "$NODE_ROLE"

cdes_metadata_path = "./tests/demo_data"

[celery]
worker_concurrency = 1
task_soft_time_limit = 30
task_time_limit = 60
run_udf_soft_time_limit = 60
run_udf_time_limit = 120

[rabbitmq]
ip = "$RABBITMQ_IP"
port = "$RABBITMQ_PORT"
user = "user"
password = "password"
vhost = "user_vhost"

[monetdb]
ip = "$MONETDB_IP"
port = "$MONETDB_PORT"
database = "db"
username = "monetdb"
password = "monetdb"
